version: '3.4'

services:
  database:
    image: postgres
    env_file:
      - dbenv
    ports:
      - 5432:5432
  
  application:
    image: istchallengerenaldi
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - dbenv
    ports:
      - 8080:8080
